const USERS_FIELD_MAP = {
  _id: '_id',
  email: 'email',
  username: 'username',
  hash: 'hash',
  accentColor: 'accent_color',
  timeFormat: 'time_format',
  dateFormat: 'date_format',
  lastSelectedList: 'last_selected_list',
  role: 'role',
  adminGrantedAt: 'admin_granted_at',
  spotifyAuth: 'spotify_auth',
  tidalAuth: 'tidal_auth',
  tidalCountry: 'tidal_country',
  musicService: 'music_service',
  resetToken: 'reset_token',
  resetExpires: 'reset_expires',
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  lastActivity: 'last_activity',
  lastfmAuth: 'lastfm_auth',
  listSetupDismissedUntil: 'list_setup_dismissed_until',
  lastfmUsername: 'lastfm_username',
  approvalStatus: 'approval_status',
  columnVisibility: 'column_visibility',
};

module.exports = {
  USERS_FIELD_MAP,
};
